on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.SCALA_OJISAN_APP_ID }}
          private_key: ${{ secrets.SCALA_OJISAN_PRIVATE_KEY }}
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          author-email: "78953241+scala-ojisan[bot]@users.noreply.github.com"
          author-name: "scala-ojisan[bot]"
          repos-file: "./repos.md"
